apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.fullname" . }}-service
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "web-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
