apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: your-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: your-docker-image  # Замените на имя вашего Docker-образа
          ports:
            - containerPort: 8000
          env:
            - name: AUTHOR
              value: by Talgat
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          readinessProbe:
            httpGet:
              path: /hostname
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /hostname
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
