apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: your-namespace
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
